FROM openjdk:8-jdk-alpine

MAINTAINER Tien Tran

ENV JETTY_VERSION=9.4.32.v20200930 \
    TZ=Australia/Melbourne \
    STORE_PASS=changme \
    KEY_PASS=changme \
    WAITFOR_HOST= \
    WAITFOR_PORT= \
    TIMEOUT=120

COPY rootfs /

RUN apk --no-cache add coreutils bash && \
    chmod +x /build.sh && /build.sh && rm -rf /build.sh

WORKDIR /opt/jetty

EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
CMD ["gosu", "alpine", "java -jar start.jar jetty.home=$PWD"]
